# This workflow is for a nightly run against WildFly upstream

name: Java CI with Maven

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00 UTC

jobs:
  wildfly-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    outputs:
      wildfly-version: ${{steps.version.outputs.wildfly-version}}
    steps:
      - name: Checkout WildFly
        uses: actions/checkout@v2
        with:
          repository: wildfly/wildfly
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build WildFly
        run: mvn clean install -DskipTests '-Dcheckstyle.skip=true' '-Denforcer.skip=true' -pl galleon-pack -am
      - id: version
        if: runner.os == 'Linux'
        run: echo "::set-output name=wildfly-version::$(mvn -B help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"

  wildfly-arquillin-build:
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest]
        # Currently windows-latest isn't really working from some reason. The SNAPSHOT cannot be found
        os: [ubuntu-latest]
        java: ['1.8', '11']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn clean verify '-Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dversion.org.wildfly.full=${{needs.wildfly-build.outputs.wildfly-version}}' '-Dversion.org.wildfly=${{needs.wildfly-build.outputs.wildfly-version}}'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'
